# Generated by Django 5.2.15 on 2026-07-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_status_options_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationentry',
            options={'verbose_name': 'Запись об операции', 'verbose_name_plural': 'Записи об операциях'},
        ),
        migrations.AlterField(
            model_name='operationentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operationentry',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='operationentry',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='operationentry',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='operationentry',
            name='sum',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='operationentry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.type', verbose_name='Тип'),
        ),
    ]
